# general config 
device: 'cuda:0'
gamma : 0.99
buffer_size : 100000
exploration_fraction : 0.3
start_e : 1
end_e : 0.1
divide_input : false

train_distil_frequency : 100
train_teacher_frequency : 1
teacher_epochs : 1

distil_buffer_size : 30000
distil_method : 'kl'    # kl mse
kl_tau : 0.01           # kl_sharp ratio

c51:
  target_network_frequency: 5000
  tau : 0.5
  batch_size : 32
  learning_rate: 2.5e-4
  # when the teacher agent is c51 
  v_min : -10
  v_max : 10
  n_atoms : 51
dqn:
  target_network_frequency: 1000
  tau : 0.5
  batch_size : 32
  learning_rate: 2e-5

# --- Distilled Student related config
distil:
  simple:
    learning_rate: 1e-4
    batch_size: 32
    distil_epochs : 100
