# general config 
device: 'cuda:0'
gamma : 0.99
buffer_size : 10000
exploration_fraction : 0.1
start_e : 1
end_e : 0.01 


train_teacher_frequency : 4

c51:
  target_network_frequency: 5000
  tau : 0.5
  batch_size : 32
  learning_rate: 2.5e-4
  # when the teacher agent is c51 
  v_min : -10
  v_max : 10
  n_atoms : 51
dqn:
  target_network_frequency: 1000
  tau : 0.5
  batch_size : 32
  learning_rate: 1e-4

# --- Distilled Student related config
distiled:
  a:
    ab: 1
    bc: 1
  b: 
    ab: 1
    bc: 1
  c: 
    ab: 1
    bc: 1