# general config 
device: 'cuda:0'
gamma : 0.99
buffer_size : 100000
exploration_fraction : 0.1
start_e : 1
end_e : 0.01 

train_distil_frequency : 1000
train_teacher_frequency: 1000
teacher_epochs : 200

distil_buffer_size : 10000
distil_method : 'kl'    # kl mse
kl_tau : 0.01           # kl_sharp ratio

c51:
  target_network_frequency: 5000
  batch_size : 32
  learning_rate: 2.5e-4
  # when the teacher agent is c51 
  v_min : -10
  v_max : 10
  n_atoms : 51
dqn:
  target_network_frequency: 1000
  batch_size : 32
  learning_rate: 1e-4

# --- Distilled Student related config
distil:
  simple:
    learning_rate: 1e-3
    batch_size: 64
    distil_epochs : 100
